name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 设置要部署的分支

permissions:
  contents: write # 添加写入权限

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: List files in public directory
        run: ls -la public/

      - name: Build
        run: pnpm build

      - name: List output directory
        run: ls -la out/

      - name: Add .nojekyll file
        run: touch out/.nojekyll

      - name: Copy CNAME file
        run: cp public/CNAME out/ || echo "CNAME file not found, creating..." && echo "yeargao.site" > out/CNAME

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out # 构建输出目录
          branch: gh-pages # 部署的目标分支
          clean: true # 清理旧文件
          token: ${{ secrets.GITHUB_TOKEN }} # 使用GitHub提供的token
